// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ProjectManagerWebApi.Models
{
    public partial class Projects
    {
        public Projects()
        {
            Tasks = new HashSet<Tasks>();
        }

        public int ProjectId { get; set; }
        public string ProjectName { get; set; }
        public DateTime DateAdded { get; set; }
        [JsonIgnore]
        public virtual ICollection<Tasks> Tasks { get; set; }
    }
}