// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProjectManagerWebApi.Models
{
    public partial class sp_Insert_ProjectResult
    {
        public int ProjectId { get; set; }
        public string ProjectName { get; set; }
        public DateTime DateAdded { get; set; }
    }
}
